proxies:
  - name: "SS Server"
    type: ss
    server: 161.35.90.99
    port: 8388
    cipher: chacha20-ietf-poly1305
    password: ubuntu-161.35.90.99

proxy-groups:
  - name: "Proxy Group"
    type: select
    proxies:
      - "SS Server"

rules:
  - MATCH,Proxy Group